//! User aggregate repository.
//!
//! [`UserRepository`] is the abstract interface used by handlers. The concrete
//! [`PgUserRepository`] implements it on top of `sqlx::PgPool`.
//!
//! All handlers that touch the `users` table will eventually go through this
//! trait. Phase 2 of #163 migrates the `auth`, `admin`, and `permissions`
//! modules; later phases will leave the trait stable and just add more
//! repository traits (e.g. `MerchandiseRepository` in Phase 3).

use crate::error::AppError;
use crate::generated::ymatch::User;
use crate::handlers::mappers::user_from_row;
use crate::repositories::RepositoryFuture;
use chrono::{DateTime, Utc};
use sqlx::{PgPool, Row};

/// Verified user aggregate used by [`crate::services::PermissionPolicy`].
///
/// Distinct from the proto [`User`] message: it carries only the fields
/// needed for permission checks (id, role, is_banned). The struct is
/// constructed by [`UserRepository::get_verified`] and includes a resolved
/// "is the user effectively banned right now" flag, including the
/// temporary-ban-expiry logic.
#[derive(Debug, Clone)]
pub struct VerifiedUser {
    pub id: i32,
    pub role: String,
    pub is_banned: bool,
}

/// Lookup modes supported by [`UserRepository::get_by_username`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UsernameLookup {
    /// Standard account lookup; returns the password hash alongside the
    /// user (used by `auth::login`).
    WithPassword,
    /// Profile lookup; omits the password hash.
    Public,
}

/// Result of [`UserRepository::get_by_username`]: the user plus an optional
/// password hash (only present in [`UsernameLookup::WithPassword`] mode).
pub type UserWithHash = (User, Option<String>);

/// Abstract user repository.
///
/// All methods return [`RepositoryFuture`] so the trait is `dyn`-compatible
/// and can be wrapped in `Arc<dyn UserRepository>` for axum state.
pub trait UserRepository: Send + Sync {
    /// Fetch a user by primary key, returning `None` if not found.
    fn get_by_id<'a>(&'a self, id: i32) -> RepositoryFuture<'a, Result<Option<User>, AppError>>;

    /// Fetch a user by username.
    ///
    /// With [`UsernameLookup::WithPassword`] returns `(User, Option<String>)`
    /// where the `Option<String>` is the password hash (`None` for guest /
    /// OAuth-style accounts). With [`UsernameLookup::Public`] returns
    /// `(User, ())` — the hash is never read.
    fn get_by_username<'a>(
        &'a self,
        username: &'a str,
        mode: UsernameLookup,
    ) -> RepositoryFuture<'a, Result<Option<UserWithHash>, AppError>>;

    /// Fetch a user by their device-bound UUID. Used by guest login.
    fn get_by_uuid<'a>(
        &'a self,
        uuid: &'a str,
    ) -> RepositoryFuture<'a, Result<Option<User>, AppError>>;

    /// Create a guest user. `username` is generated by the caller.
    fn create_guest<'a>(
        &'a self,
        username: &'a str,
        uuid: &'a str,
        device_token: Option<&'a str>,
    ) -> RepositoryFuture<'a, Result<User, AppError>>;

    /// Create a user with a password.
    fn create_with_password<'a>(
        &'a self,
        username: &'a str,
        password_hash: &'a str,
        device_token: Option<&'a str>,
    ) -> RepositoryFuture<'a, Result<User, AppError>>;

    /// List all users (admin only — caller is responsible for the role check).
    fn list_all<'a>(&'a self) -> RepositoryFuture<'a, Result<Vec<User>, AppError>>;

    /// Update a user's username. Returns `None` if the user does not exist.
    fn update_username<'a>(
        &'a self,
        id: i32,
        username: &'a str,
    ) -> RepositoryFuture<'a, Result<Option<User>, AppError>>;

    /// Update a user's device token. Returns `None` if the user does not exist.
    fn update_device_token<'a>(
        &'a self,
        id: i32,
        device_token: Option<&'a str>,
    ) -> RepositoryFuture<'a, Result<Option<()>, AppError>>;

    /// Set a user's role. Returns `None` if the user does not exist.
    fn set_role<'a>(
        &'a self,
        id: i32,
        role: &'a str,
    ) -> RepositoryFuture<'a, Result<Option<()>, AppError>>;

    /// Set a user's ban state. `banned_until: None` means a permanent ban
    /// (when `banned=true`) or the absence of a ban (when `banned=false`).
    fn set_ban<'a>(
        &'a self,
        id: i32,
        banned: bool,
        reason: Option<&'a str>,
        banned_until: Option<DateTime<Utc>>,
    ) -> RepositoryFuture<'a, Result<Option<()>, AppError>>;

    /// Fetch a user and resolve the effective ban state (including
    /// temporary-ban expiry). Returns `None` if the user does not exist.
    fn get_verified<'a>(
        &'a self,
        id: i32,
    ) -> RepositoryFuture<'a, Result<Option<VerifiedUser>, AppError>>;
}

/// PostgreSQL implementation of [`UserRepository`].
pub struct PgUserRepository {
    pool: PgPool,
}

impl PgUserRepository {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

/// Standard SELECT list for the `users` table. Used by all read paths.
const USER_COLUMNS: &str =
    "id, username, uuid, device_token, created_at, role, is_banned, ban_reason, banned_until";

impl UserRepository for PgUserRepository {
    fn get_by_id<'a>(&'a self, id: i32) -> RepositoryFuture<'a, Result<Option<User>, AppError>> {
        Box::pin(async move {
            let row = sqlx::query(&format!("SELECT {} FROM users WHERE id = $1", USER_COLUMNS))
                .bind(id)
                .fetch_optional(&self.pool)
                .await?;
            Ok(row.as_ref().map(user_from_row))
        })
    }

    fn get_by_username<'a>(
        &'a self,
        username: &'a str,
        mode: UsernameLookup,
    ) -> RepositoryFuture<'a, Result<Option<UserWithHash>, AppError>> {
        Box::pin(async move {
            let sql = match mode {
                UsernameLookup::WithPassword => format!(
                    "SELECT {}, password_hash FROM users WHERE username = $1",
                    USER_COLUMNS
                ),
                UsernameLookup::Public => {
                    format!("SELECT {} FROM users WHERE username = $1", USER_COLUMNS)
                }
            };
            let row = sqlx::query(&sql)
                .bind(username)
                .fetch_optional(&self.pool)
                .await?;
            Ok(row.map(|r| {
                let user = user_from_row(&r);
                let password_hash = match mode {
                    UsernameLookup::WithPassword => r.get("password_hash"),
                    UsernameLookup::Public => None,
                };
                (user, password_hash)
            }))
        })
    }

    fn get_by_uuid<'a>(
        &'a self,
        uuid: &'a str,
    ) -> RepositoryFuture<'a, Result<Option<User>, AppError>> {
        Box::pin(async move {
            let row = sqlx::query(&format!(
                "SELECT {} FROM users WHERE uuid = $1",
                USER_COLUMNS
            ))
            .bind(uuid)
            .fetch_optional(&self.pool)
            .await?;
            Ok(row.as_ref().map(user_from_row))
        })
    }

    fn create_guest<'a>(
        &'a self,
        username: &'a str,
        uuid: &'a str,
        device_token: Option<&'a str>,
    ) -> RepositoryFuture<'a, Result<User, AppError>> {
        Box::pin(async move {
            let row = sqlx::query(&format!(
                "INSERT INTO users (username, uuid, device_token) VALUES ($1, $2, $3) RETURNING {}",
                USER_COLUMNS
            ))
            .bind(username)
            .bind(uuid)
            .bind(device_token)
            .fetch_one(&self.pool)
            .await?;
            Ok(user_from_row(&row))
        })
    }

    fn create_with_password<'a>(
        &'a self,
        username: &'a str,
        password_hash: &'a str,
        device_token: Option<&'a str>,
    ) -> RepositoryFuture<'a, Result<User, AppError>> {
        Box::pin(async move {
            let row = sqlx::query(&format!(
                "INSERT INTO users (username, password_hash, device_token) VALUES ($1, $2, $3) RETURNING {}",
                USER_COLUMNS
            ))
            .bind(username)
            .bind(password_hash)
            .bind(device_token)
            .fetch_one(&self.pool)
            .await?;
            Ok(user_from_row(&row))
        })
    }

    fn list_all<'a>(&'a self) -> RepositoryFuture<'a, Result<Vec<User>, AppError>> {
        Box::pin(async move {
            let rows = sqlx::query(&format!("SELECT {} FROM users", USER_COLUMNS))
                .fetch_all(&self.pool)
                .await?;
            Ok(rows.iter().map(user_from_row).collect())
        })
    }

    fn update_username<'a>(
        &'a self,
        id: i32,
        username: &'a str,
    ) -> RepositoryFuture<'a, Result<Option<User>, AppError>> {
        Box::pin(async move {
            let row = sqlx::query(&format!(
                "UPDATE users SET username = $1 WHERE id = $2 RETURNING {}",
                USER_COLUMNS
            ))
            .bind(username)
            .bind(id)
            .fetch_optional(&self.pool)
            .await?;
            Ok(row.as_ref().map(user_from_row))
        })
    }

    fn update_device_token<'a>(
        &'a self,
        id: i32,
        device_token: Option<&'a str>,
    ) -> RepositoryFuture<'a, Result<Option<()>, AppError>> {
        Box::pin(async move {
            let affected = sqlx::query("UPDATE users SET device_token = $1 WHERE id = $2")
                .bind(device_token)
                .bind(id)
                .execute(&self.pool)
                .await?
                .rows_affected();
            if affected == 0 {
                Ok(None)
            } else {
                Ok(Some(()))
            }
        })
    }

    fn set_role<'a>(
        &'a self,
        id: i32,
        role: &'a str,
    ) -> RepositoryFuture<'a, Result<Option<()>, AppError>> {
        Box::pin(async move {
            let affected = sqlx::query("UPDATE users SET role = $1 WHERE id = $2")
                .bind(role)
                .bind(id)
                .execute(&self.pool)
                .await?
                .rows_affected();
            if affected == 0 {
                Ok(None)
            } else {
                Ok(Some(()))
            }
        })
    }

    fn set_ban<'a>(
        &'a self,
        id: i32,
        banned: bool,
        reason: Option<&'a str>,
        banned_until: Option<DateTime<Utc>>,
    ) -> RepositoryFuture<'a, Result<Option<()>, AppError>> {
        Box::pin(async move {
            let affected = if banned {
                sqlx::query(
                    "UPDATE users SET is_banned = true, ban_reason = $1, banned_until = $2 WHERE id = $3",
                )
                .bind(reason)
                .bind(banned_until)
                .bind(id)
                .execute(&self.pool)
                .await?
                .rows_affected()
            } else {
                sqlx::query(
                    "UPDATE users SET is_banned = false, ban_reason = NULL, banned_until = NULL WHERE id = $1",
                )
                .bind(id)
                .execute(&self.pool)
                .await?
                .rows_affected()
            };
            if affected == 0 {
                Ok(None)
            } else {
                Ok(Some(()))
            }
        })
    }

    fn get_verified<'a>(
        &'a self,
        id: i32,
    ) -> RepositoryFuture<'a, Result<Option<VerifiedUser>, AppError>> {
        Box::pin(async move {
            let row =
                sqlx::query("SELECT id, role, is_banned, banned_until FROM users WHERE id = $1")
                    .bind(id)
                    .fetch_optional(&self.pool)
                    .await?;
            let Some(row) = row else { return Ok(None) };

            let is_banned: bool = row.get("is_banned");
            let banned_until: Option<DateTime<Utc>> = row.get("banned_until");

            // Temporary-ban expiry logic: if a banned_until timestamp is in
            // the past, the ban is no longer effective.
            let effectively_banned = if is_banned {
                match banned_until {
                    Some(until) => Utc::now() < until,
                    None => true, // permanent ban
                }
            } else {
                false
            };

            Ok(Some(VerifiedUser {
                id: row.get("id"),
                role: row.get("role"),
                is_banned: effectively_banned,
            }))
        })
    }
}

#[cfg(test)]
pub mod mock {
    //! In-process test double for [`UserRepository`].
    //!
    //! The full test suite (`backend/tests/api_tests.rs`) exercises
    //! `PgUserRepository` against a live PostgreSQL. The mock here is for
    //! `PermissionPolicy` unit tests in `services::permissions`, which need
    //! to verify policy decisions without spinning up the DB.
    use super::*;

    pub struct MockUserRepository {
        pub users: std::collections::HashMap<i32, VerifiedUser>,
    }

    impl MockUserRepository {
        pub fn new() -> Self {
            Self {
                users: std::collections::HashMap::new(),
            }
        }

        pub fn with_user(mut self, id: i32, role: &str, is_banned: bool) -> Self {
            self.users.insert(
                id,
                VerifiedUser {
                    id,
                    role: role.to_string(),
                    is_banned,
                },
            );
            self
        }
    }

    impl UserRepository for MockUserRepository {
        fn get_by_id<'a>(
            &'a self,
            _id: i32,
        ) -> RepositoryFuture<'a, Result<Option<User>, AppError>> {
            Box::pin(async move { Ok(None) })
        }
        fn get_by_username<'a>(
            &'a self,
            _username: &'a str,
            _mode: UsernameLookup,
        ) -> RepositoryFuture<'a, Result<Option<UserWithHash>, AppError>> {
            Box::pin(async move { Ok(None) })
        }
        fn get_by_uuid<'a>(
            &'a self,
            _uuid: &'a str,
        ) -> RepositoryFuture<'a, Result<Option<User>, AppError>> {
            Box::pin(async move { Ok(None) })
        }
        fn create_guest<'a>(
            &'a self,
            _username: &'a str,
            _uuid: &'a str,
            _device_token: Option<&'a str>,
        ) -> RepositoryFuture<'a, Result<User, AppError>> {
            unimplemented!()
        }
        fn create_with_password<'a>(
            &'a self,
            _username: &'a str,
            _password_hash: &'a str,
            _device_token: Option<&'a str>,
        ) -> RepositoryFuture<'a, Result<User, AppError>> {
            unimplemented!()
        }
        fn list_all<'a>(&'a self) -> RepositoryFuture<'a, Result<Vec<User>, AppError>> {
            Box::pin(async move { Ok(vec![]) })
        }
        fn update_username<'a>(
            &'a self,
            _id: i32,
            _username: &'a str,
        ) -> RepositoryFuture<'a, Result<Option<User>, AppError>> {
            Box::pin(async move { Ok(None) })
        }
        fn update_device_token<'a>(
            &'a self,
            _id: i32,
            _device_token: Option<&'a str>,
        ) -> RepositoryFuture<'a, Result<Option<()>, AppError>> {
            Box::pin(async move { Ok(None) })
        }
        fn set_role<'a>(
            &'a self,
            _id: i32,
            _role: &'a str,
        ) -> RepositoryFuture<'a, Result<Option<()>, AppError>> {
            Box::pin(async move { Ok(None) })
        }
        fn set_ban<'a>(
            &'a self,
            _id: i32,
            _banned: bool,
            _reason: Option<&'a str>,
            _banned_until: Option<DateTime<Utc>>,
        ) -> RepositoryFuture<'a, Result<Option<()>, AppError>> {
            Box::pin(async move { Ok(None) })
        }
        fn get_verified<'a>(
            &'a self,
            id: i32,
        ) -> RepositoryFuture<'a, Result<Option<VerifiedUser>, AppError>> {
            let user = self.users.get(&id).cloned();
            Box::pin(async move { Ok(user) })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verified_user_is_constructible() {
        let v = VerifiedUser {
            id: 1,
            role: "user".to_string(),
            is_banned: false,
        };
        assert_eq!(v.id, 1);
    }
}
