//! User aggregate repository.
//!
//! [`UserRepository`] owns all `users` table operations.
//!
//! Phase B-8 of #191: migrated from the previous `trait UserRepository +
//! PgUserRepository` two-type pattern to a single concrete struct,
//! matching the Phase A shape. The in-process `MockUserRepository` and
//! the `mock` module have been removed; services that need to fake a
//! user in a test now use a real `PgPool` via `#[sqlx::test]` (or
//! `PgPool::connect_lazy` for pure-logic tests that never touch the DB).
//!
//! All handlers that touch the `users` table go through this struct.

use crate::error::AppError;
use crate::generated::ymatch::User;
use crate::handlers::mappers::user_from_row;
use chrono::{DateTime, Utc};
use sqlx::{PgPool, Row};

/// Verified user aggregate used by [`crate::services::PermissionPolicy`].
///
/// Distinct from the proto [`User`] message: it carries only the fields
/// needed for permission checks (id, is_banned). The struct is constructed by
/// [`UserRepository::get_verified`] and includes a resolved "is the user
/// effectively banned right now" flag, including the temporary-ban-expiry
/// logic.
///
/// The global role is intentionally **not** a field here. Authorization reads
/// the authoritative role from `user_roles` via [`RbacService::check`]
/// (`backend/src/services/rbac.rs`), which takes a `VerifiedUser` and uses
/// only its `id`; no authz path ever needed the role on this struct (ADR 0006
/// removed the `users.role` mirror that previously populated it).
#[derive(Debug, Clone)]
pub struct VerifiedUser {
    pub id: i32,
    pub is_banned: bool,
}

/// Lookup modes supported by [`UserRepository::get_by_username`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UsernameLookup {
    /// Standard account lookup; returns the password hash alongside the
    /// user (used by `auth::login`).
    WithPassword,
    /// Profile lookup; omits the password hash.
    Public,
}

/// Result of [`UserRepository::get_by_username`]: the user plus an optional
/// password hash (only present in [`UsernameLookup::WithPassword`] mode).
pub type UserWithHash = (User, Option<String>);

pub struct UserRepository {
    pool: PgPool,
}

impl UserRepository {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Fetch a user by primary key, returning `None` if not found.
    pub async fn get_by_id(&self, id: i32) -> Result<Option<User>, AppError> {
        let row = sqlx::query(&format!("SELECT {} FROM users WHERE id = $1", USER_COLUMNS))
            .bind(id)
            .fetch_optional(&self.pool)
            .await?;
        Ok(row.as_ref().map(user_from_row))
    }

    /// Fetch a user by username.
    ///
    /// With [`UsernameLookup::WithPassword`] returns `(User, Option<String>)`
    /// where the `Option<String>` is the password hash (`None` for guest /
    /// OAuth-style accounts). With [`UsernameLookup::Public`] returns
    /// `(User, ())` — the hash is never read.
    pub async fn get_by_username(
        &self,
        username: &str,
        mode: UsernameLookup,
    ) -> Result<Option<UserWithHash>, AppError> {
        let sql = match mode {
            UsernameLookup::WithPassword => format!(
                "SELECT {}, password_hash FROM users WHERE username = $1",
                USER_COLUMNS
            ),
            UsernameLookup::Public => {
                format!("SELECT {} FROM users WHERE username = $1", USER_COLUMNS)
            }
        };
        let row = sqlx::query(&sql)
            .bind(username)
            .fetch_optional(&self.pool)
            .await?;
        Ok(row.map(|r| {
            let user = user_from_row(&r);
            let password_hash = match mode {
                UsernameLookup::WithPassword => r.get("password_hash"),
                UsernameLookup::Public => None,
            };
            (user, password_hash)
        }))
    }

    /// Fetch a user by their device-bound UUID. Used by guest login.
    pub async fn get_by_uuid(&self, uuid: &str) -> Result<Option<User>, AppError> {
        let row = sqlx::query(&format!(
            "SELECT {} FROM users WHERE uuid = $1",
            USER_COLUMNS
        ))
        .bind(uuid)
        .fetch_optional(&self.pool)
        .await?;
        Ok(row.as_ref().map(user_from_row))
    }

    /// Create a guest user. `username` is generated by the caller.
    pub async fn create_guest(
        &self,
        username: &str,
        uuid: &str,
        device_token: Option<&str>,
    ) -> Result<User, AppError> {
        let row = sqlx::query(&format!(
            "INSERT INTO users (username, uuid, device_token) VALUES ($1, $2, $3) RETURNING {}",
            USER_COLUMNS
        ))
        .bind(username)
        .bind(uuid)
        .bind(device_token)
        .fetch_one(&self.pool)
        .await?;
        Ok(user_from_row(&row))
    }

    /// Create a user with a password.
    pub async fn create_with_password(
        &self,
        username: &str,
        password_hash: &str,
        device_token: Option<&str>,
    ) -> Result<User, AppError> {
        let row = sqlx::query(&format!(
            "INSERT INTO users (username, password_hash, device_token) VALUES ($1, $2, $3) RETURNING {}",
            USER_COLUMNS
        ))
        .bind(username)
        .bind(password_hash)
        .bind(device_token)
        .fetch_one(&self.pool)
        .await?;
        Ok(user_from_row(&row))
    }

    /// List all users (admin only — caller is responsible for the role check).
    pub async fn list_all(&self) -> Result<Vec<User>, AppError> {
        let rows = sqlx::query(&format!("SELECT {} FROM users", USER_COLUMNS))
            .fetch_all(&self.pool)
            .await?;
        Ok(rows.iter().map(user_from_row).collect())
    }

    /// Update a user's username. Returns `None` if the user does not exist.
    pub async fn update_username(&self, id: i32, username: &str) -> Result<Option<User>, AppError> {
        let row = sqlx::query(&format!(
            "UPDATE users SET username = $1 WHERE id = $2 RETURNING {}",
            USER_COLUMNS
        ))
        .bind(username)
        .bind(id)
        .fetch_optional(&self.pool)
        .await?;
        Ok(row.as_ref().map(user_from_row))
    }

    /// Update a user's device token. Returns `None` if the user does not exist.
    pub async fn update_device_token(
        &self,
        id: i32,
        device_token: Option<&str>,
    ) -> Result<Option<()>, AppError> {
        let affected = sqlx::query("UPDATE users SET device_token = $1 WHERE id = $2")
            .bind(device_token)
            .bind(id)
            .execute(&self.pool)
            .await?
            .rows_affected();
        if affected == 0 {
            Ok(None)
        } else {
            Ok(Some(()))
        }
    }

    /// Set a user's *global* role. Returns `None` if the user does not exist.
    ///
    /// ADR 0006: `user_roles` (scope_type='global', scope_id=NULL) is the single
    /// source of truth for the global role — the `users.role` mirror was dropped.
    /// `proto.User.role` is derived from this row at read time (`USER_COLUMNS`),
    /// so this method writes only `user_roles`: it removes the user's prior
    /// global assignment and inserts the new `global/<role>` row in one
    /// transaction. If `role` is not a known global role in the `roles` catalog,
    /// the transaction rolls back and the caller gets `AppError::bad_request`.
    pub async fn set_role(&self, id: i32, role: &str) -> Result<Option<()>, AppError> {
        let mut tx = self.pool.begin().await?;
        // Validate the role exists in the catalog before mutating, so an
        // unknown role rolls back cleanly. (The `roles` catalog is seeded by
        // the RBAC migration and is static between migrations.)
        let role_id: Option<i32> =
            sqlx::query_scalar("SELECT id FROM roles WHERE scope_type = 'global' AND name = $1")
                .bind(role)
                .fetch_optional(&mut *tx)
                .await?;
        let Some(role_id) = role_id else {
            tx.rollback().await?;
            return Err(AppError::bad_request(format!(
                "Invalid role: {role}. Must be one of: user, moderator, admin"
            )));
        };
        // A user holds at most one global role, so delete-then-insert is
        // correct. Detect "user does not exist" via the prior global row (a
        // missing user has none); if no row existed and none is inserted for a
        // genuinely missing user, fall back to an existence check.
        let existed: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM users WHERE id = $1")
            .bind(id)
            .fetch_one(&mut *tx)
            .await?;
        if existed == 0 {
            tx.rollback().await?;
            return Ok(None);
        }
        sqlx::query(
            "DELETE FROM user_roles
             WHERE user_id = $1 AND scope_type = 'global' AND scope_id IS NULL",
        )
        .bind(id)
        .execute(&mut *tx)
        .await?;
        sqlx::query(
            "INSERT INTO user_roles (user_id, role_id, scope_type, scope_id)
             VALUES ($1, $2, 'global', NULL)
             ON CONFLICT (user_id, role_id, scope_id) DO NOTHING",
        )
        .bind(id)
        .bind(role_id)
        .execute(&mut *tx)
        .await?;
        tx.commit().await?;
        Ok(Some(()))
    }

    /// Set a user's ban state. `banned_until: None` means a permanent ban
    /// (when `banned=true`) or the absence of a ban (when `banned=false`).
    pub async fn set_ban(
        &self,
        id: i32,
        banned: bool,
        reason: Option<&str>,
        banned_until: Option<DateTime<Utc>>,
    ) -> Result<Option<()>, AppError> {
        let affected = if banned {
            sqlx::query(
                "UPDATE users SET is_banned = true, ban_reason = $1, banned_until = $2 WHERE id = $3",
            )
            .bind(reason)
            .bind(banned_until)
            .bind(id)
            .execute(&self.pool)
            .await?
            .rows_affected()
        } else {
            sqlx::query(
                "UPDATE users SET is_banned = false, ban_reason = NULL, banned_until = NULL WHERE id = $1",
            )
            .bind(id)
            .execute(&self.pool)
            .await?
            .rows_affected()
        };
        if affected == 0 {
            Ok(None)
        } else {
            Ok(Some(()))
        }
    }

    /// Fetch a user and resolve the effective ban state (including
    /// temporary-ban expiry). Returns `None` if the user does not exist.
    ///
    /// ADR 0006: this no longer reads a role — `VerifiedUser` carries only the
    /// `id` and resolved ban flag that authorization needs; the global role is
    /// read from `user_roles` by `RbacService::check`, not here.
    pub async fn get_verified(&self, id: i32) -> Result<Option<VerifiedUser>, AppError> {
        let row = sqlx::query("SELECT id, is_banned, banned_until FROM users WHERE id = $1")
            .bind(id)
            .fetch_optional(&self.pool)
            .await?;
        let Some(row) = row else { return Ok(None) };

        let is_banned: bool = row.get("is_banned");
        let banned_until: Option<DateTime<Utc>> = row.get("banned_until");

        // Temporary-ban expiry logic: if a banned_until timestamp is in
        // the past, the ban is no longer effective.
        let effectively_banned = if is_banned {
            match banned_until {
                Some(until) => Utc::now() < until,
                None => true, // permanent ban
            }
        } else {
            false
        };

        Ok(Some(VerifiedUser {
            id: row.get("id"),
            is_banned: effectively_banned,
        }))
    }
}

/// Standard SELECT list for the `users` table. Used by all read paths.
///
/// ADR 0006: the `users.role` column was dropped; `User.role` (proto field 6)
/// is now **derived** from `user_roles` at read time via the correlated
/// subquery below, aliased as `role` so [`user_from_row`] is unchanged. The
/// derivation reads the user's single global role (`scope_type='global'`,
/// `scope_id IS NULL`) with precedence `admin > moderator > user`, and falls
/// back to `'user'` (via `COALESCE`) for a guest with no global assignment —
/// preserving the old `DEFAULT 'user'` column semantics. `user_roles(user_id)`
/// is indexed (`idx_user_roles_user`), so this is one indexed lookup per fetch.
const USER_COLUMNS: &str = concat!(
    "id, username, uuid, device_token, created_at, ",
    "COALESCE((",
    "  SELECT r.name FROM user_roles ur ",
    "  JOIN roles r ON r.id = ur.role_id ",
    "  WHERE ur.user_id = users.id ",
    "    AND ur.scope_type = 'global' AND ur.scope_id IS NULL ",
    "  ORDER BY CASE r.name WHEN 'admin' THEN 0 WHEN 'moderator' THEN 1 ELSE 2 END ",
    "  LIMIT 1",
    "), 'user') AS role, ",
    "is_banned, ban_reason, banned_until"
);
