name: New Relic GitHub Actions Exporter

on:
  workflow_run:
    workflows: ["CI", "Deploy to OCI (Production)", "Deploy to OCI (Staging)", "Database Backup"]
    types: [completed]

permissions:
  actions: read
  contents: read

env:
  GHA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  GHA_RUN_ID: ${{ github.event.workflow_run.id }}
  GHA_RUN_NAME: ${{ github.event.workflow_run.name }}

jobs:
  new-relic-exporter:
    name: Export telemetry to New Relic
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v5
      - name: New Relic Exporter
        uses: newrelic-experimental/gha-new-relic-exporter@1.0.1
